config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :events do 
    collection do 
      get 'events_current_user'
    end
  end

  post ':event_id/presences' => 'presences#create'
  delete ':event_id/presences' => 'presences#destroy'

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessor :enable_facebook_post
	belongs_to :user
	has_many :presences
	has_attached_file :photo, 
		default_url: "https://s3-sa-east-1.amazonaws.com/eventsbrazil/default/:style/missing.png",
		styles: { 
			thumb: "350x250#",
			medium: "400x300#", 
			banner: "750x500#" 
		}
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates :title, :description, :date_time, :local, presence: true


	def post_facebook token, url
		if enable_facebook_post && token && user.facebook?
			Facebook.new(token).post(self, url)
		end
	end
	
end

app/models/facebook.rb
class Facebook
	attr_reader :fb_graph

	def initialize(token)
		@fb_graph = FbGraph::User.me(token)
	end


	def post event, url
		post = {
			message: 'Acabei de criar um novo evento no EventsBrazil não deixe de conferir',
		  link: url,
		  picture: event.photo.url(:original, timestamp: false),	
		  name: event.title,
		  description: event.description
		}
		@fb_graph.feed!(post)
	end

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    where(uid: auth.uid, provider: auth.provider).first_or_create
  end


  def facebook?
  	provider == "facebook"
  end
end

app/models/presence.rb
class Presence < ActiveRecord::Base
  belongs_to :user
  belongs_to :event, counter_cache: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :events
  has_one :identity
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  delegate :facebook?, to: :identity


  def self.find_for_oauth(auth, signed_in_resource = nil)
  	identity = Identity.find_for_oauth(auth)
		user = signed_in_resource ? signed_in_resource : identity.user
		if user.nil?
			email = auth.info.email
		  user = User.where(:email => email).first if email
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          email: email,
          image: auth.info.image,
          password: Devise.friendly_token[0,20]
        )
        user.save!
      end
    end
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
  protect_from_forgery with: :exception
  after_filter :set_csrf_cookie_for_ng

	def set_csrf_cookie_for_ng
	  cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
	end

	protected
		def verified_request?
	    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
	  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:edit, :update, :destroy]

  def index
    @events = Event.includes(:presences).order(created_at: :desc).page(params[:page])
  end

  def events_current_user
    @events = current_user.events.order(created_at: :desc).page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.build
  end

  def edit
    authorize @event
  end

  def create
    Event.transaction do
      @event = current_user.events.build(event_params)
      @event.presences.build(user_id: current_user.id)
      respond_to do |format|
        if @event.save
          @event.post_facebook session[:access_toke], event_url(@event)
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    authorize @event
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:photo, :title, :description, :local, :date_time, :enable_facebook_post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        auth = env["omniauth.auth"]
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)
        if @user.persisted?
          session[:access_toke] = auth.credentials.token
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :google_oauth2, :linkedin].each do |provider|
    provides_callback_for provider
  end
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :authenticate_user!
  def create
  	@event = Event.find(params[:event_id])
  	@presence = @event.presences.where(user_id: current_user.id).first_or_create
  	render json: { presences_count: @event.presences_count }
  end

  def destroy
  	event = Event.find(params[:event_id])
  	event.presences.where(user_id: current_user.id).first.destroy
  	event.reload
  	render json: { presences_count: event.presences_count }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def facebook_share
		html = if @event && action_name == "show"
			<<-HTML 
				<meta property="og:url"           content="#{ event_url(@event) }" />
		    <meta property="og:type"          content="website" />
		    <meta property="og:title"         content="#{ @event.title }" />
		    <meta property="og:description"   content="#{ @event.description }" />
		    <meta property="og:image"         content="#{ @event.photo.url(:original, timestamp: false) }" />
		    <meta name="description"					content="#{ @event.description}" />
			HTML
		else
			<<-HTML 
				<meta property="og:image" content="#{ asset_url 'logo.png' }" />
			  <meta property="og:title" content="Events Brazil" />
			  <meta property="og:site_name" content="Events Brazil"/>
			  <meta property="og:url" content="#{ root_url }" />
			  <meta property="og:type" content="website" />
			  <meta property="og:description" content="Site feito com o intuito de compartilhar eventos na área de TI em todo território brasileiro. " />
			  <meta property="og:locale" content="pt_BR" />
			  <meta name="description" content="Site feito com o intuito de compartilhar eventos na área de TI em todo território brasileiro. " />
		  HTML
		end
		html.html_safe
	end
end

app/helpers/events_helper.rb
module EventsHelper
	def share_button event
		html = <<-HTML
			<div class="col-md-12">
        <ul class="social-network social-circle">
          <li>
            <a href="https://www.facebook.com/dialog/feed?app_id=168897073442603&link=#{event_url(event)}&picture=#{event.photo.url(:original, timestamp: false)}&display=popup&name=#{event.title}&description=#{event.description}&caption=#{root_url}&redirect_uri=#{event_url(event)}" class="icoFacebook b-share-button bg" title="Facebook"><i class="fa fa-facebook"></i></a>
          </li>
          <li>
            <a href="http://twitter.com/intent/tweet?status=Não deixe de participar+#{event_url(event)}" class="icoTwitter bg" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
        </ul>       
      </div>
		HTML
		html.html_safe
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<div class="form-group">
  <%= f.label :photo %>
  <%= f.file_field :photo %>
</div>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>
<div class="row">
  <div class="form-group col-md-6">
    <%= f.label :date_time %>
    <%= f.text_field :date_time, class: "form-control" %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :local %>
    <%= f.text_field :local, class: "form-control" %>
  </div>
</div>
<div class="form-group ">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", rows: 10 %>
</div>
<% if current_user.facebook? %>
  <div class="form-group">
    <%= f.label "Postar no facebook?" %>
    <%= f.check_box :enable_facebook_post, class: "form-control" %>
  </div>  
<% end %>
<%= f.submit nil, class: "btn btn-success" %>
<% end %>

app/views/events/_list_event.html.erb
<div ng-controller="EventCtrl as eCtrl" ng-init="eCtrl.load()">
  <div infinite-scroll="eCtrl.scroll()" infinite-scroll-distance="3">
    <div class="list-group">
      <div ng-repeat="event in eCtrl.events" style="padding-bottom=20px">
        <div class="list-group-item">
          <div class="media col-md-4">
            <div class="pull-left">
              <img class="blogicon" ng-src="{{event.photo}}" />
            </div>
          </div>
          <div class="col-md-5">
            <h4 class="list-group-item-heading"><a ng-href="/events/{{event.id}}">{{ event.title }}</a></h4>
            <p class="list-group-item-text">
              {{ event.description }}
            </p>
          </div>
          <div class="col-md-3 text-center">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="ratetext">Ir</div>
                <i class="fa fa-5x fa-thumbs-o-up" ng-class="{ confirm: event.confirmed == true, unconfirm: event.confirmed == false }" ng-click="eCtrl.presence(event.id)"></i>
                <h2>{{ event.presences_count }}<small> {{ event.presences_count > 1 ? "Vão" : "Vai" }}</small></h2>
                <div id="rate1" class="sui-rating"><div id="shieldRating-range-2" class="sui-rating-range" tabindex="0" style="width: 160px; height: 16px;"><div class="sui-rating-selected" style="height: 16px; width: 116.8px;"></div><div class="sui-rating-hover" style="height:16px"></div></div></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="text-center">
	<h2>Editar evento</h2>
</div>
<hr class="star-primary">

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/events_current_user.html.erb
<div class="text-center">
	<h2>Meus eventos</h2>
</div>
<hr class="star-primary">

<table class="table table-condensed table-bordered">
<thead>
	<tr>
		<th>Título</th>
		<th>Data</th>
		<th>Local</th>
		<th>###</th>
	</tr>
</thead>
	<% @events.each do |event| %>
		<tr>
			<td><%= event.title %></td>
			<td><%= l(event.date_time, format: :short) %></td>
			<td><%= event.local %></td>
			<td>
				<%= link_to "Mais detalhes", event_path(event), class: "btn btn-xs btn-default" %>
				<%= link_to "Editar", edit_event_path(event), class: "btn btn-xs btn-warning" %>	
			</td>
		</tr>
	<% end %>
</table>

<div class="text-center">
	<%= paginate @events %>
</div>

app/views/events/index.html.erb
<%= render 'list_event' %>

app/views/events/new.html.erb
<div class="text-center">
	<h2>Novo evento</h2>
</div>
<hr class="star-primary">

<%= render 'form' %>

<%= link_to 'Voltar', events_path %>

app/views/events/show.html.erb
<div class="portfolio-modal">
  <div class="modal-content">
    <%= link_to(events_path, class: "close-modal") do %>
    <div class="lr">
      <div class="rl">
      </div>
    </div>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="modal-body">
            <h2><%= @event.title %></h2>
            <hr class="star-primary">
            <%= link_to(@event.photo.url, class: "event_image_original") do %>
            <%= image_tag @event.photo.url(:banner), class: "img-responsive img-centered" %>
            <% end %>
            <p><%= @event.description %></p>
            <ul class="list-inline item-details">
              <li>Organizador:
                <strong><a href="#"><%= @event.user.email %></a>
                </strong>
              </li>
              <li>Data:
                <strong><a href="#"><%= l(@event.date_time, format: :when) %></a>
                </strong>
              </li>
              <li>Local:
                <strong><a href="#"><%= @event.local %></a>
                </strong>
              </li>
              <% if policy(@event).update? %>
              <li>
                <strong>
                  <%= link_to "Editar", edit_event_path(@event, image: @event.photo.url, popup: true) %>
                </strong>
              </li>
              <% end %>
            </ul>
            <%= share_button @event %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<%= render 'events/list_event' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="events">
<head>
  <title>EventsBrazil</title>
  <link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path('favicon/apple-icon-57x57.png') %>">
  <link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path('favicon/apple-icon-60x60.png') %>">
  <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path('favicon/apple-icon-72x72.png') %>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path('favicon/apple-icon-76x76.png') %>">
  <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path('favicon/apple-icon-114x114.png') %>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path('favicon/apple-icon-120x120.png') %>">
  <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path('favicon/apple-icon-144x144.png') %>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path('favicon/apple-icon-152x152.png') %>">
  <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path('favicon/apple-icon-180x180.png') %>">
  <link rel="icon" type="image/png" sizes="192x192"  href="<%= asset_path('favicon/android-icon-192x192.png') %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path('favicon/favicon-32x32.png') %>">
  <link rel="icon" type="image/png" sizes="96x96" href="<%= asset_path('favicon/favicon-96x96.png') %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path('favicon/favicon-16x16.png') %>">
  <meta name="eventsbrazil-TileColor" content="#ffffff">
  <meta name="eventsbrazil-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= facebook_share %>
  <meta name="keywords" content="evento events brasil brazil ti tecnologia">
  <%= javascript_include_tag 'application' %>
</head>
<body>
<a href="https://github.com/alissonbrunosa/events">
  <img style="position: absolute; top: 0; left: 0; border: 0; z-index:21561;" src="https://camo.githubusercontent.com/8b6b8ccc6da3aa5722903da7b58eb5ab1081adee/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f6f72616e67655f6666373630302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_orange_ff7600.png">
</a>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Events Brazil", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden active">
            <a href="#page-top"></a>
          </li>
          <% if user_signed_in? %>
            <li class="page-scroll">
              <%= link_to "Meus eventos ", events_current_user_events_path %>
            </li>
            <li class="page-scroll">
              <%= link_to "Novo", new_event_path %>
            </li>
            <li class="page-scroll">
              <%= link_to "Sair", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="page-scroll">
              <%= link_to "Entrar", new_user_session_path %>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |name,msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>